### PR TITLE
Writing a check to make sure user is signed in

### LINKED ISSUE #441: Entering the profile page while not logged in causes an error due to saved graphs call.
**Describe the bug**
If a user is not logged in, when navigating to the profile page, the page causes an error due to the useEffect which calls a list of saved graphs.

**To Reproduce**
1. Launch website while not logged in.
2. Go to the Profile Page
3. See the error below:

**Expected behavior**
The profile page should show a form to log in while not logged in.

**Screenshots**
image

**Desktop (please complete the following information):**
 - Windows 10
 - Google Chrome

### PR DESCRIPTION
**Pull request by laithAwad**
A simple check before running the command for the backend to check if the user is signed in

### CODE REVIEW

**Review by lposo — APPROVED** [review]
looks good, thanks for fixing the bug.

File: Client/src/Components/Profile/ProfileView.tsx [hunk 1]
```diff
@@ -150,7 +149,8 @@ export function ProfileView() {
       const savedGraphState = await listGraphStates()
       setSavedGraphState(savedGraphState.reverse())
     }
-    callListSavedGraphStates()
+    if (user && user.email)
```
Comment (GD-Dheer) [inline Client/src/Components/Profile/ProfileView.tsx:152]: Good find. This was causing a crash real often

**Review by GD-Dheer — APPROVED** [review]
