### PR TITLE
Some file upload entry fixes

### LINKED ISSUE #150: DataUploadModel Issues
Due to the current set up of the DataUploadModel, it is unable to properly input ManyToMany relations (Author<>Publications and Material<>Dataset) plus it cannot insert into Category and Subcategory tables. 

**Solution** 
Fix the DataUploadModel to properly include the relations when inserting the appropriate publication and dataset. Possible solution might be to change referenceAuthors/material to be an array of author/material objects instead of the current storage method. 
Figure out the bug with Category/Subcategory inserts. Shifting away from the current .save method for table insertions, or fixing issues stemming from that method, may prove to be the solution.

### LINKED ISSUE #211: Duplicate Entries when Uploading Data Sets
Due to the current set up of the DataUploadModel, it will add duplicate entries for multiple tables, such as authors, compositions, categories, subcategories, among others. 

**How to Reproduce**
Upload the same JSON file twice to the DB. Then look at one of the aforementioned tables and you will see duplicate entries, as seen in the picture below of the Composition table.

image

**Expected behavior**
When an entry already exists, it should be referenced instead of creating a whole new entry. 

**Solution** 
Add in various checks to DataUploadModel to see if a various entry already exists, and if the entry exists, use that entry instead of creating a new one.

### LINKED ISSUE #228: fileUploadService does not have support for DOI, dateAccessed, and datePublished
**Describe the bug**
When a uploading a new data set via file upload, there is no support for adding a DOI, dateAccessed, and/or datePublished to a publication reference.

**To Reproduce**
1. Navigate to the File Upload page
2. Upload a dataset JSON with a DOI, dateAccessed, and datePublished, example below.
image
3. See that the dataset uploads and lacks these fields. Pictured below is the Dataset table entry, followed by the linked Publications table entry
image
image

**Expected behavior**
The data set should be uploaded and the attached publication should have a DOI, dateAccessed, and/or datePublished if they are included.

### PR DESCRIPTION
**Pull request by silent-po2**
This PR address the following bugs with file upload: #228 (no doi, dateAccessed, datePublished support), #211 (no checks for duplicate entries), and #150 (Author<>Publications and Material<>Dataset linking issue).

### CODE REVIEW

File: Server/src/models/DataUploadModel.ts [hunk 1]
```diff
@@ -14,192 +13,697 @@ import { Units } from './entities/Units';
...
+     * @param publicationTypeReceived 
+     * Publication type: string
+     */
+    async insertReferenceType(publicationTypeReceived: string): Promise<number> {
+        let publicationType = new Publicationtype();
+        publicationType.id;
+        publicationType.name = publicationTypeReceived;
+        let publicationTypeExists: any;
+        publicationTypeExists = await this.fetchReferenceTypeId(publicationTypeReceived);
+        if (publicationTypeExists != false) {
```
Comment (GD-Dheer) [inline Server/src/models/DataUploadModel.ts]: Good check before insert

File: Server/src/models/DataUploadModel.ts [hunk 2]
```diff
@@ -14,192 +13,697 @@ import { Units } from './entities/Units';
...
+     * 
+     * @param publisherReceived 
+     * Publisher name: string
+     */
+    private async fetchPublisherId(publisherReceived: string): Promise<any> {
+        let publisherExists = await this.selectPublisherIdQuery(publisherReceived)
+        if (publisherExists == undefined) {
+            publisherExists = false;
+        }
+        return publisherExists;
```
Comment (GD-Dheer) [inline Server/src/models/DataUploadModel.ts]: This can return either a rowPacket or a boolean. Is there a way we can instead return rowpacket or return nothing instead?

File: Server/src/models/DataUploadModel.ts [hunk 3]
```diff
@@ -14,192 +13,697 @@ import { Units } from './entities/Units';
...
+     * @param publisherReceived
+     * Publisher name: string 
+     */
+    async insertPublisher(publisherReceived: string): Promise<number> {
+        let publisher = new Publisher();
+        publisher.id;
+        publisher.name = publisherReceived;
+        let publisherExists: any;
+        publisherExists = await this.fetchPublisherId(publisherReceived);
+        if (publisherExists != false) {
```
Comment (GD-Dheer) [inline Server/src/models/DataUploadModel.ts]: Similarly, this could probably be if publisherExists == undefined || == null

File: Server/src/models/DataUploadModel.ts [hunk 4]
```diff
@@ -14,192 +13,697 @@ import { Units } from './entities/Units';
...
+     * 
+     * @param author 
+     * An author's full name: IAuthors
+     */
+    private async fetchAuthorIdHasMiddleName(author: IAuthors): Promise<any> {
+        let authorExists =
+            await this.selectAuthorIdQuery(author.firstname, author.lastname)
+                .andWhere('LOWER(author.middleName) = LOWER(:middleName)', { middleName: author.middlename })
+                .getRawOne();
+        if (authorExists == undefined) {
```
Comment (GD-Dheer) [inline Server/src/models/DataUploadModel.ts]: Same as the previous

File: Server/src/models/DataUploadModel.ts [hunk 5]
```diff
@@ -14,192 +13,697 @@ import { Units } from './entities/Units';
...
+     * @param publicationPages 
+     * Pages of the reference: number
+     * @param publicationVolume 
+     * Publication volume: number
+     * @param publicationYear 
+     * Publication year: number
+     */
+    private async fetchPublicationId(publicationName: string, publicationDOI: string, publicationPages: number, publicationVolume: number, publicationYear: number): Promise<any> {
+        let publicationExists = await this.selectPublicationIdQuery(publicationName, publicationDOI, publicationPages, publicationVolume, publicationYear);
+        if (publicationExists == undefined) {
```
Comment (GD-Dheer) [inline Server/src/models/DataUploadModel.ts]: Another instance

File: Server/src/models/DataUploadModel.ts [hunk 6]
```diff
@@ -14,192 +13,697 @@ import { Units } from './entities/Units';
...
+            publicationExists = false;
+        }
+        return publicationExists;
+    }
 
+    /**
+     * This method will create a Publications object and return it's ID. It will check if a duplicate 
+     * Publications exists via @fetchPublicationId and if it exists will set the
+     * Publications object to have the same ID as the existing entry. If there is no
```
Comment (GD-Dheer) [inline Server/src/models/DataUploadModel.ts:187]: Good comments here to explain whats going on A+

File: Server/src/models/DataUploadModel.ts [hunk 7]
```diff
@@ -14,192 +13,697 @@ import { Units } from './entities/Units';
...
+        publication.doi = referenceDOI;
         publication.pages = referencePages;
-        publication.publicationtypeId = preferenceTypeID;
+        publication.publicationtypeId = referenceTypeId;
         publication.publisherId = publisherNameId;
         publication.year = referenceYear;
         publication.volume = referenceVolume;
-        publication.datePublished;
-        publication.dateAccessed;
+        publication.datePublished = referenceDatePublished;
```
Comment (GD-Dheer) [inline Server/src/models/DataUploadModel.ts:221]: Handling Date issues A+

File: Server/src/services/fileUploadService.ts [hunk 8]
```diff
@@ -97,10 +100,10 @@ export class fileUploadService {
 
     //checks and validates if ref authors are strings and handles error--
     referenceAuthors = jsonObj.reference.authors;
-
     this.arrTypeValidationCheck(referenceAuthors, 'string');
+    let allAuthors: any[];
```
Comment (GD-Dheer) [inline Server/src/services/fileUploadService.ts]: Is this mappable to an Authors Interface or type? Like IAuthors

File: Server/src/services/fileUploadService.ts [hunk 9]
```diff
@@ -112,26 +115,29 @@ export class fileUploadService {
     if (referenceTitleValidation === false)
       return referenceTitleValidation + " reference title should be a string";
 
+    referenceDOI = jsonObj.reference.doi;
+    //check and validates if reference DOI is a string
+    let referenceDOIValidation = this.stringValidation(referenceDOI);
```
Comment (GD-Dheer) [inline Server/src/services/fileUploadService.ts:121]: Nice Add

**Review by GD-Dheer — CHANGES_REQUESTED** [review]
Good job knocking out several bugs. Small change and the rest looks great

File: Server/src/services/fileUploadService.ts (hunk 8 above)
Comment (silent-po2) [reply Server/src/services/fileUploadService.ts]: This array will specifically hold Authors table/entry objects. I'll see if I can specify that as the array type, uncertain if possible.

File: Server/src/models/DataUploadModel.ts (hunk 2 above)
Comment (silent-po2) [reply Server/src/models/DataUploadModel.ts]: Now that you mention it, returning nothing should do the trick, which would allow for cutting a bunch of lines of code. Good catch, I'll see if that works!

File: Server/src/services/fileUploadService.ts (hunk 8 above)
Comment (silent-po2) [reply Server/src/services/fileUploadService.ts]: Authors[] works as a type; change made

File: Server/src/models/DataUploadModel.ts (hunk 2 above)
Comment (silent-po2) [reply Server/src/models/DataUploadModel.ts]: This was a great thought, it worked perfectly!

**Comment by silent-po2** [comment]
Requested changes done, should be good to go

**Review by GD-Dheer — APPROVED** [review]
Nice! Thanks for the modifications

**Review by TiraFire — APPROVED** [review]
Looks good, glad to have these bugs fixed. The cat/subcat looks good, publications are now much better dealt with. Good job!
