### PR TITLE
Bug fix for User Approval of Data Set

### LINKED ISSUE #309: [Backend] User Approval Lacks Checks
Describe the bug:
When a user inputs a PUT request to approve a data set, they can approve any unapproved data set. 

To reproduce (account bug):
-Upload a new data set on account A
-Log in to account B
-Key in an approval request via Postman
-See that the data set is approved

To reproduce (no flag bug):
-Upload a new data set 
-Key in an approval request via Postman
-See that the data set is approved

Expected behavior:
In both cases, the approval request should fail. In the first instance, an error should be thrown saying that account B is not the uploader for account A's data set. In the second instance it should fail with a notice that the data set has not yet passed initial screening.

### PR DESCRIPTION
**Pull request by silent-po2**
This fixes a bug where when a user inputs a PUT request to approve a data set, they can approve any unapproved data set regardless of if they uploaded this data set originally and/or regardless of whether the data set has passed initial screening (aka. flagged). 

It also fixes issues related to the formatting of the approve data set routes and streamlines them.

### CODE REVIEW

File: Server/src/models/DatasetModels/DatasetApprovalModel.ts [hunk 1]
```diff
@@ -63,6 +63,26 @@ export class DatasetApprovalModel {
...
     }
 
+    async verifyUnapprovedDatasetUploader(id: number, userId: number): Promise<any> {
+        let upload = await this.connection.createQueryBuilder(Unapproveddatasets, 'unapproved_datasets')
+            .select('dataset.uploaderId', 'uploaderId')
+            .addSelect('unapproved_datasets.isFlagged', 'isFlagged')
+            .innerJoin(Dataset, 'dataset', 'dataset.id = unapproved_datasets.datasetId')
+            .where('dataset.id = :id', { id: id })
+            .getRawOne();
+        console.log(userId)
```
Comment (ratulkai93) [inline Server/src/models/DatasetModels/DatasetApprovalModel.ts]: are the console logs necessary or just for debugging?

File: Server/src/routes/DatasetRouter.ts [hunk 2]
```diff
@@ -41,12 +41,12 @@ router.get('/api/v1/userFlaggedDatasets', JWTAuthenticator.verifyJWT, (request:
...
-router.put('/api/v1/adminApprovedDataset/:datasetId', [JWTAuthenticator.verifyJWT, JWTAuthenticator.verifyAdmin], (request: Request, response: Response) => {
-    dataSetController.createAdminApprovedDatasetRequest(request, response)
+router.put('/api/v1/approveDataset/:datasetId', JWTAuthenticator.verifyJWT, (request: Request, response: Response) => {
+    dataSetController.createUserApprovedDatasetRequest(request, response)
 })
 
-router.put('/api/v1/userApprovedDataset/:datasetId', JWTAuthenticator.verifyJWT, (request: Request, response: Response) => {
-    dataSetController.createUserApprovedDatasetRequest(request, response)
+router.put('/api/v1/approveDataset', [JWTAuthenticator.verifyJWT, JWTAuthenticator.verifyAdmin], (request: Request, response: Response) => {
+    dataSetController.createAdminApprovedDatasetRequest(request, response)
```
Comment (ratulkai93) [inline Server/src/routes/DatasetRouter.ts:49]: looks pretty good

File: Server/src/services/DataSetService.ts [hunk 3]
```diff
@@ -484,7 +494,10 @@ export class DataSetService {
             this.requestResponse.message = response
             return this.requestResponse
         } catch (error) {
-            throw new InternalServerError("Something went wrong with flagging this dataset. Try again later")
+            if (error instanceof BadRequest) {
+                throw new BadRequest(error.message)
+            }
+            throw new InternalServerError("Something went wrong with flagging this data set. Try again later")
```
Comment (ratulkai93) [inline Server/src/services/DataSetService.ts:500]: good error messages

File: Server/src/services/DataSetService.ts [hunk 4]
```diff
@@ -499,21 +512,28 @@ export class DataSetService {
...
+            let response = await this.approvalModel.approveDataset(datasetId)
             this.requestResponse.statusCode = 200
             this.requestResponse.message = response
             return this.requestResponse
         } catch (error) {
-            throw new InternalServerError("Internal server error approving this dataset. Try again later")
+            if (error instanceof BadRequest) {
+                throw new BadRequest(error.message)
+            }
+            throw new InternalServerError("Data set already approved or an internal server error occured when approving data set.")
```
Comment (ratulkai93) [inline Server/src/services/DataSetService.ts:536]: nice

**Review by ratulkai93 — COMMENTED** [review]
Looks good overall. Great job

File: Server/src/models/DatasetModels/DatasetApprovalModel.ts (hunk 1 above)
Comment (silent-po2) [reply Server/src/models/DatasetModels/DatasetApprovalModel.ts]: Good catch; debugging and I missed removing those when I did a pass for logs. Removed

Comment (ratulkai93) [reply Server/src/models/DatasetModels/DatasetApprovalModel.ts]: good job

**Review by ratulkai93 — APPROVED** [review]

File: Server/src/services/DataSetService.ts [hunk 5]
```diff
@@ -345,6 +346,9 @@ export class DataSetService {
             this.requestResponse.message = response as any
             return this.requestResponse
         } catch (error) {
+            if (error instanceof NotFound) {
+                throw new NotFound(error.message)
+            }
             throw new InternalServerError("Something went wrong deleting a saved data set. Try later")
```
Comment (GD-Dheer) [inline Server/src/services/DataSetService.ts:352]: This should be wrapped. If an error of type NotFound is thrown then this will automatically thrown an InternalServerError. Instead this should be in a if else

File: Server/src/services/DataSetService.ts [hunk 6]
```diff
@@ -432,6 +436,9 @@ export class DataSetService {
             this.requestResponse.message = response as any
             return this.requestResponse
         } catch (error) {
+            if (error instanceof NotFound) {
+                throw new NotFound(error.message)
+            }
             throw new InternalServerError("Something went wrong fetching all Unapproved Datasets. Try later")
```
Comment (GD-Dheer) [inline Server/src/services/DataSetService.ts:442]: Similarly

**Review by GD-Dheer — COMMENTED** [review]
The errors are not being caught properly
