### PR TITLE
Various dataset form fixes

### LINKED ISSUE #510: [Frontend] - some dataset form fields are broken on file upload
**Describe the bug**
image

**To Reproduce**
Upload a samlple Json file and you can see the input fields look broken

**Expected behavior**
Should not be broken

### PR DESCRIPTION
**Pull request by ds161833**
- fixed issue where the subcategory wasnt selected on page load
- fixed overlapping textfields like pages, volumes, etc.
- when the form is disabled fully not show the buttons that are disabled

### CODE REVIEW

File: Client/src/Components/DatasetUpload/DatasetForm/MetaSection/MetaForm.tsx [hunk 1]
```diff
@@ -30,21 +30,21 @@ const getOptions = (options: any[]): any => {
...
 export const MetaForm = (props: IProps) => {
   const { materials, categories, editable } = props
-  const { setFieldValue } = useFormikContext()
-  const [selectedCategoryId, setSelectedCategoryId] = useState<number | null>(null)
+  const { values, setFieldValue } = useFormikContext()
 
   const getSubCategories = (categoryId: number): ISubcategoryModel[] => {
     const foundCategory = categories.find(category => category.id == categoryId)
     if (!foundCategory) {
+      console.log(categories, categoryId, 'returned empty')
```
Comment (GD-Dheer) [inline Client/src/Components/DatasetUpload/DatasetForm/MetaSection/MetaForm.tsx]: Extra log here

File: Client/src/Components/DatasetUpload/DatasetForm/MetaSection/MetaForm.tsx [hunk 2]
```diff
@@ -30,21 +30,21 @@ const getOptions = (options: any[]): any => {
...
       return []
     }
+    console.log(categories, categoryId, 'returned stuff')
```
Comment (GD-Dheer) [inline Client/src/Components/DatasetUpload/DatasetForm/MetaSection/MetaForm.tsx]: Another

**Review by GD-Dheer — APPROVED** [review]
Changes look good. A+

File: Client/src/Components/DatasetUpload/DatasetForm/MetaSection/MetaForm.tsx (hunk 2 above)
Comment (ds161833) [reply Client/src/Components/DatasetUpload/DatasetForm/MetaSection/MetaForm.tsx]: oops

**Review by silent-po2 — APPROVED** [review]
Looks good and works!
