### PR TITLE
#170 missing success msg bug fix

### LINKED ISSUE #170: Missing Success Message After Dataset File Upload
**Describe the bug**
When a successful upload of a dataset to the database via file, there is no message letting the user know of its success. 

**To Reproduce**
1. Navigate to the File Upload page
2. Upload a dataset with error
3. Realize nothing happens.

**Expected behavior**
There should be a way to confirm the dataset has been uploaded

**Additional info**
This is a bug due to the flaw causing multiple uploads of the dataset due to the user not realizing it as already been uploaded.

### PR DESCRIPTION
**Pull request by ratulkai93**
The current branch will display a success message after a successful file upload into the database. 

This also fixes a small bug for devs:
After uploading a dataset, only "U" would be logged in the console browser because of Line 28 -  "console.log(result[0])" in Client/src/Components/DataCell/DataCell.tsx . With 19fdace , the whole message is logged with "console.log(result)". The message is "Upload was successful!" (Line 203) from Server/src/services/fileUploadService.ts

### CODE REVIEW

File: Client/src/Components/DataCell/DataCell.js [hunk 1]
```diff
@@ -29,6 +30,7 @@ export default function DataCell() {
             setOpen(true)
             return
         }
+        setAlertSuccess(true)
```
Comment (GD-Dheer) [inline Client/src/Components/DataCell/DataCell.js:34]: Are we setting the alert if the user is able to input a file into the upload box or if the upload was successful?

File: Client/src/Components/DataCell/DataCell.js [hunk 2]
```diff
@@ -42,7 +44,7 @@ export default function DataCell() {
             await fetch('http://localhost:4000/dataupload', options)
                 .then(resp => resp.json())
                 .then(result => {
-                    console.log(result[0])
+                    console.log(result)
```
Comment (GD-Dheer) [inline Client/src/Components/DataCell/DataCell.js:49]: No need to log here

File: Client/src/Components/DataCell/DataCell.js [hunk 3]
```diff
@@ -66,9 +68,15 @@ export default function DataCell() {
             <Snackbar open={open} autoHideDuration={3000} onClose={handleClose}>
                 <Alert onClose={handleClose} severity="error">
                     Failed to parse file
-        </Alert>
+                </Alert>
             </Snackbar>
 
+           <Snackbar open={alertSuccess} autoHideDuration={3000} onClose={() => setAlertSuccess(false)}>
+                <Alert onClose={() => setAlertSuccess(false)} severity="success">
+                    File Successfully updated!! ^_^
```
Comment (GD-Dheer) [inline Client/src/Components/DataCell/DataCell.js]: A+

File: Client/src/Components/DataCell/DataCell.tsx [hunk 4]
```diff
@@ -25,7 +25,7 @@ export default function DataCell() {
       await fetch('http://localhost:4000/dataupload', options)
         .then(resp => resp.json())
         .then(result => {
-          console.log(result[0])
+          console.log(result)
```
Comment (GD-Dheer) [inline Client/src/Components/DataCell/DataCell.tsx:28]: Another log

File: Client/src/Components/DataCell/FileUploadForm.tsx [hunk 5]
```diff
@@ -31,6 +33,8 @@ export const FileUploadForm = (props: IProps) => {
     console.log("vF is " + validateFile + "  and vF() is " + validateFile(file))
     if (isValidFile) {
       onSubmit(file)
+      console.log('File successfully uploaded')
```
Comment (GD-Dheer) [inline Client/src/Components/DataCell/FileUploadForm.tsx:36]: Log..

File: Server/src/routes/fileUploadRouter.ts [hunk 6]
```diff
@@ -16,7 +16,7 @@ let router = Router();
  * and the file is stored in a temporary directory called tmp/json. This route is referred for processing by 
  * the service.
  */
-router.post('/dataupload', [JWTAuthenticator.verifyJWT, upload.single('file')], (request: MulterRequest, response: Response, next: NextFunction) => {
+router.post('/dataupload', upload.single('file'), (request: MulterRequest, response: Response, next: NextFunction) => {
```
Comment (GD-Dheer) [inline Server/src/routes/fileUploadRouter.ts]: This change cant be commited - has to keep JWTAuthenticator.verifyJWT...

**Review by GD-Dheer — APPROVED** [review]
Nice fix/. Thx

File: Client/src/Components/DataCell/DataCell.js (hunk 2 above)
Comment (JeremiahTee) [reply Client/src/Components/DataCell/DataCell.js:49]: I asked him to change this because the logged message was incomplete. In the console browser, after uploading a dataset, it would log "U" only instead of "Upload was successful!"

**Review by Mehrdadmaskull — APPROVED** [review]
Looks good, only comment is bring back the JWT auth

File: Client/src/Components/DataCell/DataCell.js (hunk 1 above)
Comment (ratulkai93) [reply Client/src/Components/DataCell/DataCell.js:34]: we are setting it to true if the file extension check passes (ie. file.json), so it will open the snackbar and display the success message on the page, then turn it to false.

File: Server/src/routes/fileUploadRouter.ts (hunk 6 above)
Comment (ratulkai93) [reply Server/src/routes/fileUploadRouter.ts]: Had to remove that line before because the file upload would not work when its there. its now re added on the recent commit.

File: Client/src/Components/DataCell/DataCell.js (hunk 2 above)
Comment (ratulkai93) [reply Client/src/Components/DataCell/DataCell.js:49]: I don't think its a good idea to remove the console logs at the moment since they are mostly for troubleshooting the file upload and im assuming other people are working with it as well. 
If required, i'll remove them on a future commit.
