### PR TITLE
#410 graphstate bug fix

### LINKED ISSUE #410: [Backend] - POST GraphState endpoint should return created graph ID
**Describe the bug**
Because the POST GraphState endpoint doesnt return created graph ID there is no way for FE to know which graph was created so that the user can update the graph and keep their work

**To Reproduce**
1. Click SAVE GRAPH on the graph page
2. Make changes to the graph
3. Click SAVE GRAPH
4. client hangs

**Expected behavior**
1. Click SAVE GRAPH on the graph page
2. Make changes to the graph
3. Click SAVE GRAPH
4. should say "updated successfully"

**Screenshots**

### PR DESCRIPTION
**Pull request by ratulkai93**
This PR will allow graphs to be updated properly after saving them initially, without letting the client hang.

### CODE REVIEW

**Review by GD-Dheer — APPROVED** [review]
LGTM

File: Server/src/models/GraphsModel.ts [hunk 1]
```diff
@@ -193,10 +193,10 @@ export class GraphsModel {
      * @param userEmail 
      * User email address: string
      */
-    async saveGraph(graph: IGraphStateModel, userId: number): Promise<string> {
+    async saveGraph(graph: IGraphStateModel, userId: number): Promise<number> {
         let processGraphInput = await this.processGraphInput(graph)
-        let statusMessage = await this.sendSavedGraphToDatabase(userId, processGraphInput)
-        return statusMessage
+        let statusID = await this.sendSavedGraphToDatabase(userId, processGraphInput)
```
Comment (silent-po2) [inline Server/src/models/GraphsModel.ts:198]: This is a good little touch

**Review by silent-po2 — APPROVED** [review]
LGTM
